# This workflow builds the AYAB release packages
# for Windows, Mac OSX, and Ubuntu/Debian Linux.
#
# The build starts when a version tag is pushed.
# Release assets are also uploaded as workflow
# artifacts, so that they are still available
# for test releases after the release and its
# tag have been deleted.
#
# Script adapted from https://github.com/trappitsch/fbs-release-github-actions
#
# @author Tom Price
# @date   July 2020

name: Build
on: [push, pull_request]

env:
  PYTHON_VERSION: 3.11.9

jobs:
  # see https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps
  build-appimage:
    name: Create and upload Linux AppImage release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo into AppDir
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # necessary for `git describe`

      - uses: ./.github/actions/init-environment
        id: vars

      - name: Get firmware version matching manifest
        shell: bash
        working-directory: src/main/resources/base/ayab/firmware/
        run: |
          curl --fail -O '${{ steps.vars.outputs.firmware-url }}'

      - name: Install Python modules
        run: |
          sudo apt-get install -y avrdude libasound2-dev
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -r requirements.build.txt

      - name: Convert UI and translation files
        run: |
          bash setup-environment.ps1

      - name: Relocate
        run: |
          mkdir git
          shopt -s extglob dotglob
          cp -r !(git) git
          shopt -u dotglob

      - name: Build AppImage of Python designed for manylinux
        run: |
          arch=$(uname -i)
          docker run --rm -v $PWD:/out -w /tmp \
            quay.io/pypa/manylinux_2_28_${arch}:2025.02.28-1 /bin/bash -xec '
              # Create directory where python-appimage will look for its tools
              mkdir -p $HOME/.local/bin

              # Install working appimagetool
              curl -SsLO https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -i).AppImage
              chmod +x appimagetool*.AppImage
              ./appimagetool*.AppImage --appimage-extract
              mv squashfs-root $HOME/.local/bin/.appimagetool

              # Install working patchelf
              yum --disablerepo="*" --enablerepo=epel install -y patchelf
              ln -s $(which patchelf) $HOME/.local/bin

              # Install python-appimage
              python${{steps.vars.outputs.python-minor}} -m pip install python-appimage==1.3.0

              # Build AppImage from python install in manylinux image
              python${{steps.vars.outputs.python-minor}} -m python_appimage -v build local

              # Move AppImage to working directory
              cp -v python3*.AppImage /out/python.AppImage'

      - name: Extract the AppImage
        run: |
          ./python.AppImage --appimage-extract

      - name: Move repo
        run: mv git/* squashfs-root

      - name: Install dependencies
        run: |
          cd squashfs-root
          sudo apt-get install -y avrdude libasound2-dev
          ./AppRun -m pip install --upgrade pip
          # hack to fix setup.py script with faulty include
          # ./AppRun -m pip install --global-option=build_ext --global-option="-I$(pwd)/opt/${{steps.vars.outputs.python-minor}}/include/${{steps.vars.outputs.python-minor}}" simpleaudio
          ./AppRun -m pip install -r requirements.build.txt

      - name: Add AppDir subdirectories to PATH
        run: |
          echo "usr/bin" >> $GITHUB_PATH
          echo "opt/${{steps.vars.outputs.python-minor}}/bin" >> $GITHUB_PATH

      - name: Remove unneeded files
        run: |
          rm squashfs-root/src/main/python/main/ayab/*_gui.ui
          rm squashfs-root/src/main/python/main/ayab/ayab_logo_rc.qrc
          rm squashfs-root/src/main/python/main/ayab/engine/lowercase_e_rc.qrc
          rm squashfs-root/src/main/python/main/ayab/engine/lowercase_e_reversed_rc.qrc

      - name: Replace AppRun
        run: |
          cd squashfs-root
          rm AppRun
          cp linux-build/appimage/AppRun .

      - name: Add icon
        run: |
          cd squashfs-root
          rm -f *.png
          rm -rf usr/share/icons/
          cp linux-build/appimage/ayab.png ayab.png
          mkdir -p usr/share/icons/hicolor/128x128/apps/
          cp ayab.png usr/share/icons/hicolor/128x128/apps/

      - name: Create desktop file
        run: |
          cd squashfs-root
          rm -f python*.desktop
          mkdir -p usr/share/applications/
          rm -f usr/share/applications/*.desktop
          cp linux-build/appimage/com.ayab_knitting.ayab.desktop com.ayab_knitting.ayab.desktop
          cp com.ayab_knitting.ayab.desktop usr/share/applications/com.ayab_knitting.ayab.desktop

      - name: Add metadata
        run: |
          cd squashfs-root
          mkdir -p usr/share/metainfo/
          rm -f usr/share/metainfo/*.appdata.xml
          cp linux-build/appimage/ayab.appdata.xml usr/share/metainfo/

      - name: Convert to AppImage
        run: |
          wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep appimagetool-.*-x86_64.AppImage | head -n 1 | cut -d '"' -f 2)
          chmod +x appimagetool-*-x86_64.AppImage
          chmod 755 squashfs-root
          sudo apt install appstream
          VERSION=${{steps.vars.outputs.tag}} ./appimagetool-*-x86_64.AppImage squashfs-root/
          sudo apt remove appstream
          mv ayab-${{ steps.vars.outputs.tag }}-x86_64.AppImage AYAB-${{ steps.vars.outputs.tag }}-x86_64.AppImage

      - name: Attach AppImage to release
        uses: ncipollo/release-action@v1
        if: steps.vars.outputs.do-release == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}
          commit: ${{ steps.vars.outputs.sha }}
          allowUpdates: true
          artifacts: AYAB-${{ steps.vars.outputs.tag }}-x86_64.AppImage
          artifactContentType: application/AppImage
          replacesArtifacts: true
          # Default to draft and prerelease to let a human check the release before it goes live
          draft: true
          prerelease: false
          # Avoid overwriting a release that may have been manually edited
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true

      - uses: actions/upload-artifact@v4
        with:
          name: AYAB-${{ steps.vars.outputs.tag }}-x86_64.AppImage
          path: AYAB-${{ steps.vars.outputs.tag }}-x86_64.AppImage
