# This workflow builds the AYAB release packages
# for Windows, Mac OSX, and Ubuntu/Debian Linux.
#
# The build starts when a version tag is pushed.
# Release assets are also uploaded as workflow
# artifacts, so that they are still available
# for test releases after the release and its
# tag have been deleted.
#
# Script adapted from https://github.com/trappitsch/fbs-release-github-actions
#
# @author Tom Price
# @date   July 2020

name: Build
on: [push, pull_request]

env:
  PYTHON_VERSION: 3.11.9

jobs:
  # see https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps
  build-appimage:
    name: Create and upload Linux AppImage release
    # runs-on: ubuntu-22.04
    runs-on: ubuntu-22.04-arm
    env:
      # ARCH: x86_64
      ARCH: aarch64
    container:
      image: quay.io/pypa/manylinux_2_34_aarch64:2025.02.28-1
    steps:
      - name: Checkout repo into AppDir
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # necessary for `git describe`

      - uses: ./.github/actions/init-environment
        id: vars

      - name: Get firmware version matching manifest
        shell: bash
        working-directory: src/main/resources/base/ayab/firmware/
        run: |
          curl --fail -O '${{ steps.vars.outputs.firmware-url }}'

      - name: Build AppImage of Python designed for manylinux
        shell: bash -xe
        run: |
          arch=$(uname -i)
          # Create directory where python-appimage will look for its tools
          mkdir -p $HOME/.local/bin

          # Install working appimagetool
          curl -SsLO "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-$(uname -i).AppImage"
          chmod +x appimagetool*.AppImage
          ./appimagetool*.AppImage --appimage-extract
          mv squashfs-root $HOME/.local/bin/.appimagetool.appdir.$(uname -i)
          
          # Install working patchelf
          curl -SsLO "https://github.com/NixOS/patchelf/releases/download/0.14.3/patchelf-0.14.3-$(uname -i).tar.gz"
          tar -C $HOME/.local -xvzf patchelf*.gz ./bin/patchelf

          # Install python-appimage
          python${{steps.vars.outputs.python-minor}} -m pip install python-appimage==1.3.0

          # Build AppImage from python install in manylinux image
          python${{steps.vars.outputs.python-minor}} -m python_appimage -v build local

          # Extract AppImage
          ./python3*.AppImage --appimage-extract
          shopt -s dotglob
          mv squashfs-root/* .
          rmdir squashfs-root

      - name: Add AppDir subdirectories to PATH
        run: |
          echo "$PWD/usr/bin" >> $GITHUB_PATH
          # echo "$PWD/opt/${{steps.vars.outputs.python-minor}}/bin" >> $GITHUB_PATH

      - name: Install Python modules
        run: |
          yum install -qy alsa-lib-devel
          python -m pip install -r requirements.build.txt

      - name: Convert UI and translation files
        run: |
          cat setup-environment.ps1 | grep -v genpyi | grep -v submodule | bash -x
          # bash setup-environment.ps1

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.build.txt

      - name: Remove unneeded files
        run: |
          rm src/main/python/main/ayab/*_gui.ui
          rm src/main/python/main/ayab/ayab_logo_rc.qrc
          rm src/main/python/main/ayab/engine/lowercase_e_rc.qrc
          rm src/main/python/main/ayab/engine/lowercase_e_reversed_rc.qrc

      - name: Replace AppRun
        run: |
          cp -v linux-build/appimage/AppRun .

      - name: Add icon
        run: |
          rm -rf python.png usr/share/icons/
          ln -sf linux-build/appimage/ayab.png .DirIcon

      - name: Create desktop file
        run: |
          rm -f *.desktop usr/share/applications/
          ln -s linux-build/appimage/com.ayab_knitting.ayab.desktop .

      - name: Add metadata
        run: |
          mkdir -p usr/share/metainfo/
          rm -f usr/share/metainfo/*.appdata.xml
          cp linux-build/appimage/ayab.appdata.xml usr/share/metainfo/

      - name: Convert to AppImage
        run: |
          yum install -qy appstream
          appdir=$PWD
          cd /tmp
          VERSION=${{steps.vars.outputs.tag}} $HOME/.local/bin/.appimagetool.appdir.$(uname -i)/AppRun "$appdir"
          mv ayab-${{ steps.vars.outputs.tag }}-${{ env.ARCH }}.AppImage $appdir/AYAB-${{ steps.vars.outputs.tag }}-${{ env.ARCH }}.AppImage

      - name: Attach AppImage to release
        uses: ncipollo/release-action@v1
        if: steps.vars.outputs.do-release == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}
          commit: ${{ steps.vars.outputs.sha }}
          allowUpdates: true
          artifacts: AYAB-${{ steps.vars.outputs.tag }}-${{ env.ARCH }}.AppImage
          artifactContentType: application/AppImage
          replacesArtifacts: true
          # Default to draft and prerelease to let a human check the release before it goes live
          draft: true
          prerelease: false
          # Avoid overwriting a release that may have been manually edited
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true

      - uses: actions/upload-artifact@v4
        with:
          name: AYAB-${{ steps.vars.outputs.tag }}-${{ env.ARCH }}.AppImage
          path: AYAB-${{ steps.vars.outputs.tag }}-${{ env.ARCH }}.AppImage
